name: pyclient
base: core24
version: '0.1'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description.

grade: stable
confinement: strict

plugs:
  socket-provider:
    interface: content
    ## Build fails when uncommented since
    ## deepseek-r1 isn't avaible on latest/stable yet
    # default-provider: deepseek-r1
    target: $SNAP_DATA

parts:
  src:
    source: .
    plugin: python
    python-packages:
      - openai==2.3.0

apps:
  pyclient:
    command: bin/chat
    plugs:
      - network

