name: pyclient
base: core24
version: '0.1'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description.

grade: stable
confinement: strict

plugs:
  # consuming the endpoints.json using the content-interface
  inference-endpoints:
    interface: content
    target: $SNAP_DATA/share

parts:
  src:
    source: .
    plugin: python
    python-packages:
      - openai==2.3.0

apps:
  pyclient:
    command: bin/chat
    plugs:
      - network

