name: pyclient
base: core24
version: '0.1'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description.

grade: stable
confinement: strict

plugs:
  # Consume an inference snap's status.json
  inference-snap-status:
    interface: content
    target: $SNAP_DATA/inference-snap
    # This depends on gemma3 released to latest/stable
    # default-provider: gemma3

parts:
  src:
    source: .
    plugin: python
    python-packages:
      - openai==2.3.0

apps:
  pyclient:
    command: bin/chat
    plugs:
      - network

